### ISSUE TITLE
Make deal2lkit require CXX11 by default

### ISSUE THREAD

**Issue by luca-heltai** [mathLab/deal2lkit#182]
I thought for a while about this, but there are a lot features which I think we should use by default instead of guarding for CXX11 all times.

What do you all think about this?

This would make all constructors much cleaner, instead of requiring, for example, an additional string for each parameter, we would just use `std::to_str(param)` (CXX11 only), and use a default value for `param` in the constructor, instead of the default value for the _string_ associated to the param...

**Comment by asartori86** [comment]
I like this option. We could just add a guard in the CMakeLists.txt

```
IF(NOT DEAL_II_WITH_CXX11)
  MESSAGE(FATAL_ERROR "
Error! The deal.II library found at ${DEAL_II_PATH} was not configured with
    DEAL_II_WITH_CXX11 = ON
Please recompile deal.II enabling this feature."
    )
ENDIF()
```

 I guess that the users of deal2lkit are doing advanced things with deal.II and so they have recent compiler.

**Comment by luca-heltai** [comment]
Ok. I'll close this. @asartori86 can you add the above to our CMakeLists.txt?
