### ISSUE TITLE
Document the use of the optional parameters in ParsedGridGenerator

### ISSUE THREAD

**Issue by luca-heltai** [mathLab/deal2lkit#188]
For the moment only file and rectangle have been documented. We should add documentation to all other options as well.

**Comment by ESeNonFossiIo** [comment]
PR: [#190](https://github.com/mathLab/deal2lkit/pull/190/commits)

**Comment by luca-heltai** [comment]
you can close directly an open issue by adding to the commit message "closes #190" ;)
