### ISSUE TITLE
Paper deal2lkit todos

### ISSUE THREAD

**Issue by luca-heltai** [mathLab/deal2lkit#201]
- [x] Citazioni
- [x] template
- [x] stokes
- [x] ~~navier stokes~~
- [x] output error handler
- [x] laplace
- [x] citazione pi-domus
- [x] classi escluse nelle conclusioni
- [x] copiare documentazione dall'articolo alla libreria

**Comment by luca-heltai** [comment]
Su questa lista a che punto siamo?

**Comment by ESeNonFossiIo** [comment]
- template e classi escluse non ne so nulla.
- @asartori86 stokes e navier stokes?
- per copiare la documentazione aspetto quando sottomettiamo il paper.

**Comment by asartori86** [comment]
updated :) mi ero dimenticato
