### ISSUE TITLE
Bug on Gentoo Machines

### ISSUE THREAD

**Issue by luca-heltai** [mathLab/deal2lkit#263]
Deal2lkit does not compile on Gentoo machines. There it tries to instantiate a <3,4> Triangulation and fails.

According to git bisect, 1f8a98a5f46d608f25036f23e3a9846ab009f4df is the first bad commit.

**Comment by asartori86** [comment]
questo l'ho visto stasera appena prima di andare via sul pc sissa

**Comment by asartori86** [comment]
stamattina ho fatto un pull di dealii e poi deal2lkit ha dato quest'errore. chissà se è collegato al bug di step 26

**Comment by luca-heltai** [comment]
The fix didn't work...

**Comment by asartori86** [comment]
:( almeno sul pc della sissa l'ha risolto. riesci a riportare tutto il testo di errore?

**Comment by luca-heltai** [comment]
Clean build directory => compiled. :+1:
