### ISSUE TITLE
Imex and ida time output

### ISSUE THREAD

**Issue by ESeNonFossiIo** [mathLab/deal2lkit#265]
Output of imex and ida is not "parallel-friendly". (I am running a code with 80 processes and I have 80 lines for every time step...)
I would like to allow the user to change the output (output stream at least). Any idea? 
My ideas:
- pass the stream as argument (does it work for every stream? ConditionalStream?)
- use a signal (how to handle time variable?)
- use a friend function (is it a good choice?)

**Comment by luca-heltai** [comment]
The simplest approach would be to make them, by default, output only on processor 0. No need to make anything fancier...
