### ISSUE TITLE
git commit leads to a full recompilation

### ISSUE THREAD

**Issue by asartori86** [mathLab/deal2lkit#275]
when I git commit or git checkout I need to recompile the whole library. Any hints on where/what should I check?

do you have the same behavior?

**Comment by luca-heltai** [comment]
Do you use ninja? Ninja should be a little smarter about what to compile. Unless you include everywhere the file containing git information (which in deal.II is version.h)

**Comment by asartori86** [comment]
> Unless you include everywhere the file containing git information (which in deal.II is version.h)

this is the point! thanks! patch incoming
