### ISSUE TITLE
Upstream ParameterAcceptor

### ISSUE THREAD

**Issue by tamiko** [mathLab/deal2lkit#302]
Hi all,

I had a quick look at the `ParameterAcceptor` class (I remember the discussion I had with @luca-heltai about it). I absolutely love it.

@luca-heltai I haven't realized at all how beautifully self-contained this little trick is.

Therefore, I kindly request that this is upstreamed to deal.II. Opinions?

**Comment by tamiko** [comment]
@luca-heltai I will do a pull request with a couple of improvements before we attempt to port back to deal.II :-]

**Comment by asartori86** [comment]
Hi Matthias, glad to hear from you here :)

We had the chance to discuss about it with @bangerth when he was here and he opened an issue as well :)

https://github.com/dealii/dealii/issues/2268

ParameterAcceptor requires that all the objects derived from it must be constructed at construction time, which is a specific requirement that works quite well for our applications but it is a too specific design for deal.II I guess. But we can always improve it :)

with @luca-heltai we also thought about using boost::signals2::signal to connect to declare and parse_parameters

**Comment by luca-heltai** [comment]
Done.
