### ISSUE TITLE
Guard assimp source files.

### ISSUE THREAD

**Issue by luca-heltai** [mathLab/deal2lkit#306]
If assimp is not found, assimp source files should be guarded:

```
/home/heltai/src/deal2lkit/source/assimp_interface.cc:21:62: fatal error: assimp/Importer.hpp: No such file or directory
```

**Comment by asartori86** [comment]
@luca-heltai have you included `<deal2lkit/config.h>` before? that file is guarded with `#ifdef D2K_WITH_ASSIMP`..

**Comment by asartori86** [comment]
@luca-heltai what is the status of this?

**Comment by luca-heltai** [comment]
This is inside deal2lkit, and the error appears when compiling deal2lkit without assimp...

**Comment by asartori86** [comment]
I do not have assimp and I've never seen that error

**Comment by asartori86** [comment]
p.s. also Travis compiles and installs **without** assimp

**Comment by luca-heltai** [comment]
By looking at the source code everything should be fine... I'll reopen if necessary.
