### ISSUE TITLE
set "stable" branch as default? git submodules?

### ISSUE THREAD

**Issue by asartori86** [mathLab/deal2lkit#355]
what do you think to set the "stable" branch as default? and all the development is done in a "devel" branch?

what if we we handle the required working version of deal.II with a git submodule? (we could do the same also for pi-DoMUS having deal2lkit as well as a submodule

**Comment by luca-heltai** [comment]
Git submodules are a nightmare (and badly implemented, IMHO). I'd rather avoid them. As for the development branch, I don't have preferences...
