### ISSUE TITLE
Compatibility with current dev version of deal.ii

### ISSUE THREAD

**Issue by GivAlz** [mathLab/deal2lkit#369]
The developing version of deal.II has introduced a few changes which make it not compatible with the current deal2lkit:
-  FETools::get_fe_by_name returns now `std::unique_ptr<FiniteElement<dim, spacedim> >` and not `FiniteElement< dim, spacedim > *` ( https://www.dealii.org/developer/doxygen/deal.II/namespaceFETools.html )
-  GridGenerator::hyper_sphere now requires only spacedim ( https://www.dealii.org/developer/doxygen/deal.II/namespaceGridGenerator.html#afd9c56e4acc9c02af1113754fde80cde )
- HyperSheel is becoming deprecate ( https://www.dealii.org/developer/doxygen/deal.II/classHyperShellBoundary.html ), so I guess in the future it should be removed

I can easily fix the hyper_sphere thing, by changing `GridGenerator::hyper_sphere<dim,dim+1>` to `GridGenerator::hyper_sphere<dim+1>`; but it would be better to make it require spacedim directly (potentially breaking compatibility with older versions...and I guess more code should need to be modified).

As for the pointer problem it seems a bit more complicated to solve. Any suggestion?

**Comment by luca-heltai** [comment]
If you make the change, and the testsuite passes, I'd be ok with it.

Make a PR with the needed changes.

**Comment by luca-heltai** [comment]
Fixed.
