### ISSUE TITLE
deal2lkit make error

### ISSUE THREAD

**Issue by mashsquad777** [mathLab/deal2lkit#381]
Dear developers,
                             I am new in deal.ii and want to use interfaceing for complex problems handling in it. I have chosen "deal2lkit" for this purpose however after cmake when I use make command the deal2lkit gives the following error:

/home/muhammad/software/deal2lkit-8.5/source/kinsol_interface.cc: In member function ‘int deal2lkit::KINSOLInterface<VEC>::solve(VEC&)’:
/home/muhammad/software/deal2lkit-8.5/source/kinsol_interface.cc:370:46: error: ‘KIN_FP’ was not declared in this scope
     status = KINSol(kin_mem, this->solution, KIN_FP, u_scale, f_scale);
                                              ^
/home/muhammad/software/deal2lkit-8.5/source/kinsol_interface.cc:372:46: error: ‘KIN_PICARD’ was not declared in this scope
     status = KINSol(kin_mem, this->solution, KIN_PICARD, u_scale, f_scale);
                                              ^
/home/muhammad/software/deal2lkit-8.5/source/kinsol_interface.cc: In instantiation of ‘void deal2lkit::KINSOLInterface<VEC>::initialize_solver(VEC&) [with VEC = dealii::BlockVector<double>]’:
/home/muhammad/software/deal2lkit-8.5/source/kinsol_interface.cc:459:27:   required from here
/home/muhammad/software/deal2lkit-8.5/source/kinsol_interface.cc:327:27: error: no matches converting function ‘kinsol_solve_linear_system’ to type ‘int (*)(struct KINMemRec*, N_Vector, N_Vector, realtype*) {aka int (*)(struct KINMemRec*, struct _generic_N_Vector*, struct _generic_N_Vector*, double*)}’
       KIN_mem->kin_lsolve = kinsol_solve_linear_system<VEC>;
                           ^
/home/muhammad/software/deal2lkit-8.5/source/kinsol_interface.cc:80:7: note: candidate is: template<class VEC> int deal2lkit::{anonymous}::kinsol_solve_linear_system(KINMem, N_Vector, N_Vector, double*, double*)
   int kinsol_solve_linear_system(KINMem kin_mem,
       ^
CMakeFiles/deal2lkit.dir/build.make:302: recipe for target 'CMakeFiles/deal2lkit.dir/source/kinsol_interface.cc.o' failed
make[2]: *** [CMakeFiles/deal2lkit.dir/source/kinsol_interface.cc.o] Error 1
CMakeFiles/Makefile2:99: recipe for target 'CMakeFiles/deal2lkit.dir/all' failed
make[1]: *** [CMakeFiles/deal2lkit.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

I am using version 8.5.0 for both deal.ii and deal2lkit and also tried with later and previous versions but still facing errors. Any help would be appreciated. Thanks in advance!

**Comment by luca-heltai** [comment]
I could not reproduce. Moved the sundials interface to deal.II
