### ISSUE TITLE
Compatibility issue with Sundials version newer than 3.0.0

### ISSUE THREAD

**Issue by qwyin** [mathLab/deal2lkit#382]
Dear developer,

Thanks for the wonderful work. I am using Dealii 9.0.1 compiled with Sundials 3.2.1. Now I am trying to compile deal2lkit with Sundials on. However, the following interface files are missing starting from Sundials 3.0.0:

#include <ida/ida_spgmr.h>
#include <ida/ida_spbcgs.h>
#include <ida/ida_sptfqmr.h>

Is there any way to easily solve this problem?

Thanks!

Best regards,
Qing

**Comment by luca-heltai** [comment]
Fixed by moving sundials interface into deal.II
