### ISSUE TITLE
Component Interpretation in ParsedDataOut

### ISSUE THREAD

**Issue by luca-heltai** [mathLab/deal2lkit#43]
The function add_data_vector in DataOut accepts also a `DataComponentInterpretation`.

Our `ParsedDataOut` doesn't. We should add one which automatically uses the names passed using the parameters.

For example: names = `u,u,p`, then the first two components should be `part_of_a_vector`: 

https://www.dealii.org/8.2.1/doxygen/deal.II/namespaceDataComponentInterpretation.html

**Comment by nicolacavallini** [comment]
Fatto!
