### ISSUE TITLE
Add support for DataPostProcessor

### ISSUE THREAD

**Issue by luca-heltai** [mathLab/deal2lkit#44]
The `ParsedDataOut` class does not have a member function `add_data_vector` which accepts a `DataPostprocessor`. This should be added, so that compatibility one-to-one can be ensured with `DataOut`.

```
template <typename DH>
void add_data_vector (const VECTOR &data, 
                       const DataPostprocessor< DH::space_dimension > &data_postprocessor, etc. etc.);
```

**Comment by asartori86** [comment]
e se ParsedDataOut fosse derivata da DataPostprocessor, riscrive la sua funzione virtuale `compute_derived_quantities_vector` che chiama una `std::function` che poi verrà sovrascritta dall'utente

**Comment by luca-heltai** [comment]
Perché derivarla da DataPostProcessor?

**Comment by asartori86** [comment]
così ho già al suo interno tutto

**Comment by asartori86** [comment]
se non ho capito male come funziona datapostprocessor, tu ti fai una classe derivata da lui, sovrascrivi le sue funzioni virtuali e poi lo passi al data_out

**Comment by luca-heltai** [comment]
La relazione dovrebbe essere HAS-A, non IS-A. ParsedDataOut si prende cmq quasi tutto dall'esterno. Il suo ruolo, fino ad ora, è stato semplicemente di encapsulare DataOut. Infatti ha tutte le interfacce di DataOut (add_data_vector). Basta aggiungere la funzione che chiama add_data_vector con il datapostprocessor aggiuntivo. Niente di più. Complicare questa classe, facendola derivata da datapostprocessor, non ha senso, se poi devi **comunque** sovrascrivere i membri. Tanto vale farlo esternamente.

**Comment by luca-heltai** [comment]
per questo issue, ci vogliono 5 righe di codice. non complichiamoci la vita...

**Comment by luca-heltai** [comment]
che già è complicata...

**Comment by luca-heltai** [comment]
:D

**Comment by asartori86** [comment]
:D

**Comment by luca-heltai** [comment]
avrei fatto prima a scrivere il codice invece del commento sopra...

**Comment by luca-heltai** [comment]
:D

**Comment by luca-heltai** [comment]
era un esercizio per NC, ma lui non ha colto la palla al balzo... ;)

**Comment by luca-heltai** [comment]
Neanche le legge più queste mail...
