### ISSUE TITLE
run_dir as parameter in Parsed DataOut

### ISSUE THREAD

**Issue by luca-heltai** [mathLab/deal2lkit#52]
At the moment, the argument `run_dir`, which is passed at build time to `ParsedDataOut`, does not appear in the parameter file, making it impossible for users to disable, at run time, the creation of one directory per execution. 

This, among other things, makes it impossible to write non-failing tests, since ParsedDataOut will log in `deallog` where it's going to write, and this will change at every run.

`run_dir` should become a member variable, and the code which is now in the constructor should be put inside the virtual function `parse_parameters_call_back()`, which is called automatically by `ParameterAcceptor` any time a parameter file is parsed.

Add this line in `declare_parameters()`:

``` C++
  add_parameter(prm, &base_name, "Incremental run prefix", run_dir, Patterns::Anything());
```

after you added `run_dir` as a member variable of ParsedDataOut. 

You will also have to copy all new outputs to their tests/*output counterpart....

**Comment by ESeNonFossiIo** [comment]
I think this issues could be cloded
