### ISSUE TITLE
Cannot find Boost libraries (CMake 2.8.12.2)

### ISSUE THREAD

**Issue by kbzowski** [mathLab/deal2lkit#96]
CMake 2.8.12.2 is unable to find Boost libraries until I replace
FIND_PACKAGE(BOOST)
with
FIND_PACKAGE(Boost)

**Comment by luca-heltai** [comment]
Mauro, can you make a few tests, and see if this works also for us? If yes, can you submit a patch? Thanks.

**Comment by ESeNonFossiIo** [comment]
Yup! @kbzowski is right. (Thank you!) 
We should change it. I am working on this bug but it seems that there are several little bugs linked to it.
As soon as possible I will submit a patch.

**Comment by luca-heltai** [comment]
In the dealii mailing list, this question was just answered:

```
SET (BOOST_ROOT "${BOOST_DIR}")

FIND_PACKAGE (Boost 1.58 COMPONENTS bzip2 filesystem ... and some more libs)

where $BOOST_DIR is set in the cmake call

cmake -DBOOST_DIR="/path/to/boost"

Then you have to include headers

INCLUDE_DIRECTORIES (your_headers ${BOOST_INCLUDE_DIRS})

and link your target

TARGET_LINK_LIBRARIES (your_lib ${BOOST_LIBRARIES})

Maybe this help.

Best,
Martin
```

**Comment by luca-heltai** [comment]
do we do this here, mauro?

**Comment by ESeNonFossiIo** [comment]
I opened a pull request. 
This PR should fix the bug.

**Comment by luca-heltai** [comment]
@kbzowski can you see if the latest version works for you?
